/**
 * Configuration specific to a single 3D printable layer.
 * These settings can be adjusted per-layer by the user.
 */
export interface LayerConfig {
  id: string; // Unique identifier for this layer (e.g., UUID)
  name: string; // User-defined name for the layer (e.g., "Layer 1 - Dark Blue")

  // Color information
  originalColor: string; // The dominant color extracted from the image for this layer (e.g., HEX or RGB string)
  filamentColorHex: string; // User-selected filament color for this layer (HEX string, for display and export metadata)

  // Physical dimensions and position
  layerHeightMm: number; // Custom height of this specific layer in millimeters
  zOffsetMm: number; // Z-offset position relative to the base of the stack in millimeters

  // 3D Preview specific settings
  isVisible: boolean; // Toggle visibility in 3D preview

  // Data representing the 2D geometry of this layer (e.g., SVG path data, or reference to a generated mask)
  // This would typically be generated by the backend.
  pathData?: string; // Example: SVG path data for this layer's geometry

  // The layer's own shape unioned with every layer stacked above it - this is the
  // shape that actually gets extruded/printed, since material below a raised
  // feature must be present regardless of that feature's color. Derived server-side
  // from `pathData` + stacking order; never hand-edited. Falls back to `pathData`
  // while a recompute is in flight or hasn't run yet.
  accumulatedPathData?: string;

  // Present only on a layer produced by merging others - the original individual
  // layers as they were immediately before the merge, in their original relative
  // order, so the merge can be undone. Always leaf layers (a merge of an
  // already-merged layer flattens its mergedFrom rather than nesting), and never
  // set on a layer that hasn't been merged.
  mergedFrom?: LayerConfig[];

  // A synthetic, non-extracted rectangle spanning the full image canvas, meant to be
  // printed in clear/natural filament as the bottommost layer so it diffuses the
  // backlight evenly before it reaches the color layers above. Added/removed via a
  // dedicated toggle, not part of the normal color-extraction or luminance ordering -
  // it's always forced to the bottom regardless of its (light) color.
  isDiffuser?: boolean;

  // A layer synthesized server-side from the source image's transparent region (an
  // "outside/background" fill color chosen at upload time), rather than extracted from
  // opaque pixels via clustering. Unlike isDiffuser, it participates normally in the
  // luminance-based stacking order - only its origin/name differ from an extracted layer.
  isBackgroundFill?: boolean;
}
