/**
 * Defines the types of projects supported by stack3d.
 * This allows for architectural extensibility using a Strategy/Factory pattern.
 */
export type ProjectType = 'LIGHTBOX' | 'XMAS_ORNAMENT'; // Add more as needed

/**
 * Base configuration for any project type.
 * Contains common settings applicable across all project types.
 */
export interface ProjectConfig {
  id: string; // Unique identifier for the project (e.g., UUID)
  name: string; // User-defined name for the project (e.g., "My First Lightbox")
  projectType: ProjectType; // The specific type of project
  createdAt: Date; // Timestamp when the project was created
  updatedAt: Date; // Timestamp when the project was last updated

  // Common physical dimensions for the final output
  globalWidthMm: number; // Global width of the final output in millimeters
  globalHeightMm: number; // Global height of the final output in millimeters
  baseThicknessMm: number; // Thickness of the optional base plate in millimeters

  imageSourceUrl: string; // URL or path to the original 2D image (PNG/SVG)
  // Potentially add common settings like:
  // resolutionDpi: number; // DPI for image processing
  // exportFormat: 'STL' | '3MF'; // Preferred export format
}

/**
 * Configuration specific to a single 3D printable layer.
 * These settings can be adjusted per-layer by the user.
 */
export interface LayerConfig {
  id: string; // Unique identifier for this layer (e.g., UUID)
  name: string; // User-defined name for the layer (e.g., "Layer 1 - Dark Blue")

  // Color information
  originalColor: string; // The dominant color extracted from the image for this layer (e.g., HEX or RGB string)
  filamentColorHex: string; // User-selected filament color for this layer (HEX string, for display and export metadata)

  // Physical dimensions and position
  layerHeightMm: number; // Custom height of this specific layer in millimeters
  zOffsetMm: number; // Z-offset position relative to the base of the stack in millimeters

  // 3D Preview specific settings
  opacity: number; // Opacity/translucency for 3D preview (0.0 - 1.0)
  isVisible: boolean; // Toggle visibility in 3D preview

  // Data representing the 2D geometry of this layer (e.g., SVG path data, or reference to a generated mask)
  // This would typically be generated by the backend.
  // pathData?: string; // Example: SVG path data for this layer's geometry
}

/**
 * Configuration specific to the 'LIGHTBOX' project type.
 * Extends ProjectConfig with lightbox-specific properties.
 */
export interface LightboxConfig extends ProjectConfig {
  projectType: 'LIGHTBOX';
  // Lightbox-specific properties, e.g., for the surrounding frame
  frameBorderThicknessMm: number; // Thickness of the outer frame border
  // ... any other settings unique to lightboxes
}

/**
 * Configuration specific to the 'XMAS_ORNAMENT' project type.
 * Extends ProjectConfig with ornament-specific properties.
 */
export interface OrnamentConfig extends ProjectConfig {
  projectType: 'XMAS_ORNAMENT';
  // Ornament-specific properties, e.g., for circular shape and hanging loop
  diameterMm: number; // Diameter of the circular ornament
  loopHoleDiameterMm: number; // Diameter of the hanging loop hole
  loopHoleOffsetMm: number; // Offset of the loop hole from the top edge
  // ... any other settings unique to ornaments
}

/**
 * Represents the overall state of a project, including its configuration
 * and the list of generated layers, along with UI-specific state.
 */
export interface ProjectState {
  project: ProjectConfig | LightboxConfig | OrnamentConfig; // The specific project configuration
  layers: LayerConfig[]; // Array of configurations for each generated layer
  // UI-specific state for the 3D preview
  currentViewMode: 'stacked' | 'exploded'; // Controls how layers are displayed in 3D
  backlightEnabled: boolean; // Toggle for backlight simulation in 3D preview
}
